keys:
  - &admin_azoller age1wyr7dkcfl5vzasthy03dgvcd9nvnk22y9r8mj6rsgzhajvu7yylqhsramc
  - &server_node1 age1q9yz0l8f5urfk3hpmm83gsguzqegmje4u79yypxk3jnx6nemp4jq5wt4hx
  - &server_node2 age1a9w577x524pedf5j5q3zccl9u822el3z9l59hvwl8hzwuddl4anshlekpq
  - &server_node3 age1zfwth66a4p6gkpdq0vv3h2m0c90lhv0nf0ptj57zm3739m7cgagqn8wajk
  - &server_node4 age14ghqk6nxj6f93607x6wfu23acgfha3dyk5vrtcutr4pcwhngw5cqt5q0pw
  - &server_node5 age1d8np0d9s5ajqascptulxy43x2z6css60rgve4qq7tpv88qp7e3jsq2gj9c
  - &server_main-server age1wyr7dkcfl5vzasthy03dgvcd9nvnk22y9r8mj6rsgzhajvu7yylqhsramc
  - &server_az-us-hetzner age1msrp5qhcy4mg2jmlw8mkyzntjxtrn7xradmravpcvwyml907qqsq9eq4gm
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
